### ISSUE TITLE
Абсолютний шлях

### ISSUE THREAD

**Issue by anry-das** [marharita08/Gradebook#2]
Бажано уникати використовавання абсолютних шляхів. Наприклад так
`<li><a href="/Gradebook/viewAllClasses?page=1" class="fa fa-users">Class list</a></li>`
Томущо при зміні шляху встановлення (Deploy path) для додатку потрібно буде змінити також це значення в багатьох місцях. Зазвичай шляхи вказують відносно кореня:
`<li><a href="viewAllClasses?page=1" class="fa fa-users">Class list</a></li>`
_(це скоріше рекомендація, ніж дефект)_

**Comment by marharita08** [comment]
5bc2937
